name: Go Backend CI
on:
  push:
    branches:
    - main

jobs:
  build_and_run:
    name: Build and Run Go Backend
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.5'

    - name: Fetch Dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build ./...

    # - name: Run Tests
    #   run: go test ./...

    - name: Start Go Backend
      run: |
        # Start your Go backend API here
        ./crud-project &