name: Go Backend CI
on:
  push:
    branches:
    - main

jobs:
  build_and_run:
    name: Build and Run Go Backend
    runs-on: self-hosted
    # services:
    #   docker:
    #     image: docker:dind
    #     options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.5'

    - name: Fetch Dependencies
      run: go get -v -t -d .

    - name: Build
      run: go build .
    
    - name: Prepare new Docker image
      run: docker build -t go-backend .
    
    - name: Remove the previous Backend Container
      run: |
        CONTAINER_ID=$(docker ps -q -f "label=backend")
        if [ -n "$CONTAINER_ID" ]; then
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID
        fi
        
    - name: Deploy with Docker
      run: |
        # Run the Docker container in detached mode, mapping port 8080 from the container to the host
        docker run -d -l backend -p 8080:8080 go-backend