name: Go Backend CI
on:
  push:
    branches:
    - main

jobs:
  build_and_run:
    name: Build and Run Go Backend
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.5'

    - name: Fetch Dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build ./...

    # - name: Run Tests
    #   run: go test ./...

    - name: Deploy with Docker
        run: |
          # Build the Docker image using the Dockerfile in the current directory
          docker build -t go-backend .
          # Run the Docker container in detached mode, mapping port 8080 from the container to the host
          docker run -d -p 8080:8080 go-backend
